import type { Movie } from "./movies"

const ytThumb = (id: string) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`
const ytUrl = (id: string) => `https://www.youtube.com/watch?v=${id}`

export const AI_FILMS: Movie[] = [
    {
        id: "ai_film_1",
        title: "ASTITVA",
        poster_url: ytThumb("hpi2WFCLzjw"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Sagar Chogale, Anurag Tiwari & Prasad Gori",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("hpi2WFCLzjw"),
    },
    {
        id: "ai_film_2",
        title: "AMRIT",
        poster_url: ytThumb("xquvfrVfB3Q"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Bharat Parmar, Aashish B. & Nimish Choubey",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("xquvfrVfB3Q"),
    },
    {
        id: "ai_film_3",
        title: "THE AGE OF RAGE",
        poster_url: ytThumb("BWm1-yOhe4s"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Keyur Kajavadara",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("BWm1-yOhe4s"),
    },
    {
        id: "ai_film_4",
        title: "MEENA",
        poster_url: ytThumb("79O8YiN3zDA"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Priyanshu Ratnakar, Gaurav Karn & Riya Sondhiya",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("79O8YiN3zDA"),
    },
    {
        id: "ai_film_5",
        title: "SPECTRUM",
        poster_url: ytThumb("BNLZqX2ELXw"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Amir Diba, Yassir Diba & Alexander Nalmbantis",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("BNLZqX2ELXw"),
    },
    {
        id: "ai_film_6",
        title: "OVERTIME",
        poster_url: ytThumb("ywh_LpwlTOE"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Konark Marwaha & Abhishek Tanwar",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("ywh_LpwlTOE"),
    },
    {
        id: "ai_film_7",
        title: "PROMISE",
        poster_url: ytThumb("kEmQdm0T9Yc"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Sheikh Ansaruddin, Ishan Gupta & Praveen Raju",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("kEmQdm0T9Yc"),
    },
    {
        id: "ai_film_8",
        title: "I DIDN'T FORGET TODAY",
        poster_url: ytThumb("WdSzqpCPnVs"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Aditya Dhondiba Jadhav, Yash Rajesh Singh Rajput & Yogesh Ashok Yannawar",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("WdSzqpCPnVs"),
    },
    {
        id: "ai_film_9",
        title: "ALL THAT REMAINS",
        poster_url: ytThumb("1Zo22-hguPA"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Abhishek Shelar, Yash Gaikwad & Radha Deshmukh",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("1Zo22-hguPA"),
    },
    {
        id: "ai_film_10",
        title: "TOMORROW'S GODS",
        poster_url: ytThumb("NOY8nIb878c"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Govind G, Nikhil C R & Thomas James",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("NOY8nIb878c"),
    },
    {
        id: "ai_film_11",
        title: "PAMBARAM",
        poster_url: ytThumb("qIGprO331QM"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Yadu Krishnan & Bhavana Rao",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("qIGprO331QM"),
    },
    {
        id: "ai_film_12",
        title: "42",
        poster_url: ytThumb("79TQmPx0Dwc"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Manan Dua, Kalyan Mada & Ankush",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("79TQmPx0Dwc"),
    },
    {
        id: "ai_film_13",
        title: "THE IMMORTAL'S CHOICE",
        poster_url: ytThumb("NwbopyhASkM"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Shivani D",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("NwbopyhASkM"),
    },
    {
        id: "ai_film_14",
        title: "KODAK BRAND FILM",
        poster_url: ytThumb("5J1QrZDIx2c"),
        genre: ["AI Film"],
        year: 2025,
        overview: "Satyam Kumar",
        imdb_rating: 0,
        mood: "ai_films",
        ott_providers: [],
        youtube_url: ytUrl("5J1QrZDIx2c"),
    },
]
