-- Create Rooms table
create table public.rooms (
  code text primary key,
  created_at timestamptz default now(),
  status text not null default 'waiting', -- waiting, active, finished
  mode text not null default 'solo' -- solo, dual
);

-- Create Participants table
create table public.participants (
  id uuid primary key default gen_random_uuid(),
  room_code text references public.rooms(code) on delete cascade not null,
  user_id uuid not null, -- Anonymous user ID from client
  last_seen timestamptz default now()
);

-- Create Swipes table
create table public.swipes (
  id bigint generated by default as identity primary key,
  room_code text references public.rooms(code) on delete cascade not null,
  user_id uuid not null,
  movie_id text not null,
  direction text not null, -- 'left' or 'right'
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.rooms enable row level security;
alter table public.participants enable row level security;
alter table public.swipes enable row level security;

-- Policies (Open for anonymous MVP, but good to have structure)
-- Allow anyone to read/write rooms (for creation and joining)
create policy "Public access to rooms"
  on public.rooms for all
  using (true)
  with check (true);

-- Allow anyone to read/write participants
create policy "Public access to participants"
  on public.participants for all
  using (true)
  with check (true);

-- Allow anyone to read/write swipes
create policy "Public access to swipes"
  on public.swipes for all
  using (true)
  with check (true);

-- Realtime Setup
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;

alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.participants;
alter publication supabase_realtime add table public.swipes;
